### ISSUE TITLE
Compile with Apple clang and constexpr complains

### ISSUE THREAD

**Issue by svbt** [GaryHughes/crocofix#3]
Hi @GaryHughes,

I have been trying to compile `crocofix` with Apple Clang latest (15) on MAC.

And seeing errors related to constexpr.

`/Users/panpaliamahen/github/fix/crocofix/libcrocofixdictionary/fix42_fields.hpp:51:56: error: constexpr variable 'Buy' must be initialized by a constant expression
    static constexpr crocofix::dictionary::field_value Buy = crocofix::dictionary::field_value("Buy", "B");`

all declaration similar to below are errors

`    static constexpr crocofix::dictionary::field_value Buy = crocofix::dictionary::field_value("Buy", "B");
    static constexpr crocofix::dictionary::field_value Sell = crocofix::dictionary::field_value("Sell", "S");
    static constexpr crocofix::dictionary::field_value Trade = crocofix::dictionary::field_value("Trade", "T");
    static constexpr crocofix::dictionary::field_value Cross = crocofix::dictionary::field_value("Cross", "X");`

I have tried to change

`constexpr field_value(std::string_view name, const char* value) noexcept`
to
`constexpr field_value(std::string_view name, std::string_view value) noexcept`

but didn't make any difference.

Am I missing something here?

Thanks,
Mahendra

**Comment by GaryHughes** [comment]
How have you installed clang? Can you please give show the output from  the following commands?

`which clang`
`clang --version`

**Comment by svbt** [comment]
I have installed llvm@15 and used as custom compiler option in CLION IDE.

`/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/Applications/CLion.app/Contents/bin/ninja/mac/ninja -DCMAKE_C_COMPILER=/usr/local/opt/llvm@15/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm@15/bin/clang++ -DBOOST_ROOT=/usr/local/opt/boost -G Ninja /Users/panpaliamahen/github/fix/crocofix
-- The C compiler identification is Clang 15.0.7
-- The CXX compiler identification is Clang 15.0.7`

**Comment by GaryHughes** [comment]
Ok, I generally only test with clang bundled with Xcode. Let me install and have a look.

**Comment by svbt** [comment]
Sure, I have also tried with Xcode toolchain version Clang 14 and had same issue.

**Comment by GaryHughes** [comment]
I think this is due to how you are compiling, if you look in the root of the project there is script called build_clang.sh that specifies all the required options. I've tested this with clang 14.0.3 shipped with Xcode and with llvm 16 installed via homebrew. I haven't tried building in CLion before so I'll do that and provide instructions if I get it working.

**Comment by GaryHughes** [comment]
I tried CLion by setting the CMake options to -DCMAKE_TOOLCHAIN_FILE=clang_toolchain.cmake and it builds, please try this and see how you go.

**Comment by svbt** [comment]
thanks @GaryHughes. 
Though I have been using llvm@15 and some clang-tidy checks fails with newer llvm toolchain.

They can be fixed in code but also you can suppress those checks if you want?
`-readability-identifier-length,-misc-const-correctness`

Let me know if you need any help in fixing this or creating a pull request?

**Comment by GaryHughes** [comment]
No problem, I've updated the project to use llvm@16 over the last couple of days and fixed those errors so it should compile cleanly now. If you do find any more I'm happy to take a PR, please prefer a code fix or localised NOLINT over a global clang-tidy suppression.
